# Generated by Django 4.1 on 2022-08-31 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frase',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
    ]
