# Generated by Django 3.2.15 on 2023-01-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposalario',
            name='salario',
            field=models.FloatField(default=0),
        ),
    ]
