# Generated by Django 3.2.15 on 2023-01-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_tiposalario_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dpi',
            field=models.IntegerField(default=0, max_length=15, unique=True),
        ),
    ]
