# Generated by Django 3.2.15 on 2023-01-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dpi',
            field=models.CharField(max_length=13),
        ),
    ]
