# Generated by Django 3.2.15 on 2022-12-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imphijas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imphija',
            name='de',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='imphija',
            name='pieza',
            field=models.IntegerField(),
        ),
    ]
