# Generated by Django 3.2.16 on 2023-11-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True, verbose_name='Codigo Cliente')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('formapago', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GuiasEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('codigo', models.CharField(max_length=9)),
                ('cliente', models.CharField(max_length=300)),
                ('tipo_envio', models.CharField(choices=[('CONTRA ENTREGA', 'CONTRA ENTREGA'), ('MANIFIESTOS', 'MANIFIESTOS'), ('GUIA MADRE', 'GUIA MADRE'), ('GUIA HIJA', 'GUIA HIJA')], max_length=20)),
                ('numini', models.IntegerField(default=0, unique=True)),
                ('numfin', models.IntegerField(default=0, unique=True)),
                ('totenvio', models.IntegerField(default=0)),
                ('fpago', models.CharField(choices=[('POR COBRAR', 'POR COBRAR'), ('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('PREPAGO', 'PREPAGO'), ('COMPARTIDA', 'COMPARTIDA'), ('CORTESIA', 'CORTESIA'), ('TALONARIO', 'TALONARIO'), ('GUIA EN BLANCO', 'GUIA EN BLANCO')], max_length=20)),
                ('entregado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'GuiasEnvs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_lote', models.IntegerField(default=0, unique=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('manifiesto_local', models.IntegerField(default=0)),
                ('observaciones', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
