# Generated by Django 4.1 on 2022-08-28 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('no_lote', models.IntegerField(default=0, unique=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('manifiesto_local', models.IntegerField(default=0)),
                ('observaciones', models.TextField(max_length=100)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuiasEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('codigo', models.CharField(max_length=9)),
                ('cliente', models.CharField(max_length=300)),
                ('tipo_envio', models.IntegerField(choices=[(0, 'CONTRAENTREGA'), (1, 'MANIFIESTOS'), (0, 'GUIA MADRE'), (0, 'GUIA HIJA'), (0, 'GUIA EN BLANCO')])),
                ('numini', models.IntegerField(default=0, unique=True)),
                ('numfin', models.IntegerField(default=0, unique=True)),
                ('totenvio', models.IntegerField(default=0)),
                ('entregado', models.BooleanField(default=False)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
