# Generated by Django 4.1 on 2022-08-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiasenv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiasenv',
            name='fpago',
            field=models.IntegerField(choices=[[0, 'POR COBRAR'], [1, 'CONTADO'], [2, 'CREDITO'], [3, 'PREPAGO'], [4, 'CREDITO X COBRAR'], [5, 'CONTADO X COBRAR'], [6, 'CREDITO X CREDITO'], [7, 'CORTESIA'], [8, 'TALONARIO']], default=1),
            preserve_default=False,
        ),
    ]
