# Generated by Django 4.2.8 on 2023-12-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiasenv', '0002_cliente_estado_cliente_fc_cliente_fm_cliente_uc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='formapago',
            field=models.CharField(choices=[('POR COBRAR', 'POR COBRAR'), ('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('PREPAGO', 'PREPAGO'), ('COMPARTIDA', 'COMPARTIDA'), ('CORTESIA', 'CORTESIA'), ('TALONARIO', 'TALONARIO'), ('GUIA EN BLANCO', 'GUIA EN BLANCO'), ('CONTRA ENTREGA', 'CONTRA ENTREGA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guiasenv',
            name='fpago',
            field=models.CharField(choices=[('POR COBRAR', 'POR COBRAR'), ('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('PREPAGO', 'PREPAGO'), ('COMPARTIDA', 'COMPARTIDA'), ('CORTESIA', 'CORTESIA'), ('TALONARIO', 'TALONARIO'), ('GUIA EN BLANCO', 'GUIA EN BLANCO'), ('CONTRA ENTREGA', 'CONTRA ENTREGA')], max_length=20),
        ),
    ]
