# Generated by Django 4.1 on 2022-08-29 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guiasenv', '0002_guiasenv_fpago'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lotes',
            new_name='Lote',
        ),
        migrations.AlterModelOptions(
            name='guiasenv',
            options={'verbose_name_plural': 'GuiasEnvs'},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterField(
            model_name='guiasenv',
            name='fecha',
            field=models.DateField(),
        ),
    ]
