# Generated by Django 4.2.8 on 2024-02-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiasenv', '0003_alter_cliente_options_alter_cliente_formapago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='origen',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
