# Generated by Django 4.2.8 on 2023-12-13 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpGuias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField()),
                ('codigo_cliente', models.CharField(max_length=8)),
                ('remitente', models.CharField(max_length=200, verbose_name='Nombre Remitente')),
                ('dirrem', models.CharField(max_length=300, verbose_name='Direccion Remitente')),
                ('tel', models.CharField(max_length=9, verbose_name='No. Telefono')),
                ('zona', models.CharField(max_length=2, verbose_name='Zona')),
                ('muni', models.CharField(max_length=50, verbose_name='Municipio')),
                ('origen', models.CharField(max_length=50, verbose_name='Origen')),
                ('ruta', models.CharField(max_length=3, verbose_name='Ruta')),
                ('codigo_desti', models.CharField(max_length=8)),
                ('destinatario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Destinatario')),
                ('dirdes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Direccion Destinatario')),
                ('teldes', models.CharField(blank=True, max_length=9, null=True, verbose_name='No. Telefono')),
                ('zonades', models.CharField(max_length=2, verbose_name='Zona')),
                ('munides', models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio')),
                ('destino', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo Destino')),
                ('rutades', models.CharField(blank=True, max_length=3, null=True, verbose_name='Ruta')),
                ('fpago', models.IntegerField(choices=[[0, 'POR COBRAR'], [1, 'CONTADO'], [2, 'CREDITO'], [3, 'PREPAGO'], [4, 'CREDITO X COBRAR'], [5, 'CONTADO X COBRAR'], [6, 'CREDITO X CREDITO'], [7, 'CORTESIA']], verbose_name='FORMA DE PAGO')),
                ('numini', models.IntegerField(default=0, unique=True, verbose_name='Numero inicial')),
                ('numfin', models.IntegerField(default=0, unique=True, verbose_name='Numero Final')),
                ('totalimp', models.IntegerField(default=0, verbose_name='Total Guías A Imprimir')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impresion de Guías',
                'verbose_name_plural': 'Impresiones de Guías',
            },
        ),
    ]
