# Generated by Django 4.2.8 on 2023-12-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impguias',
            name='fpago',
            field=models.IntegerField(choices=[[0, 'POR COBRAR'], [1, 'CONTADO'], [2, 'CREDITO'], [3, 'PREPAGO'], [4, 'CREDITO X COBRAR'], [5, 'CONTADO X COBRAR'], [6, 'CREDITO X CREDITO'], [7, 'CORTESIA'], [8, 'CONTRA ENTREGA']], null=True, verbose_name='FORMA DE PAGO'),
        ),
    ]
