# Generated by Django 4.2.8 on 2023-12-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impa', '0002_alter_impguias_fpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impguias',
            name='fecha',
            field=models.DateField(),
        ),
    ]
