# Generated by Django 4.2.8 on 2023-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impa', '0004_alter_impguias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impguias',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='impguias',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='No. Telefono'),
        ),
    ]
