# Generated by Django 4.2.8 on 2023-12-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impa', '0005_alter_impguias_fecha_alter_impguias_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impguias',
            name='fpago',
            field=models.CharField(choices=[['POR COBRAR', 'POR COBRAR'], ['CONTADO', 'CONTADO'], ['CREDITO', 'CREDITO'], ['PREPAGO', 'PREPAGO'], ['CREDITO X COBRAR', 'CREDITO X COBRAR'], ['CONTADO X COBRAR', 'CONTADO X COBRAR'], ['CREDITO X CREDITO', 'CREDITO X CREDITO'], ['CORTESIA', 'CORTESIA'], ['CONTRA ENTREGA', 'CONTRA ENTREGA']], max_length=20, verbose_name='FORMA DE PAGO'),
        ),
    ]
