# Generated by Django 3.2.16 on 2023-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porvee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
